// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineStore.Context;

#nullable disable

namespace OnlineStore.Migrations
{
    [DbContext(typeof(myContext))]
    [Migration("20250913171305_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineStore.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "Newest iPhones",
                            CategoryName = "Apple"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "Latest Samsung Galaxy Phones",
                            CategoryName = "Samsung"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDescription = "Flagship & current Xiaomi phones",
                            CategoryName = "Xiaomi"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryDescription = "Latest and flagship OPPO phones",
                            CategoryName = "OPPO"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryDescription = "New Honor smartphones",
                            CategoryName = "Honor"
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Apple 2025 flagship, best camera & performance",
                            ImagePath = "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2025/09/iPhone-17-Pro-Max2.jpg",
                            Price = 1399f,
                            Quantity = 50,
                            Title = "iPhone 17 Pro Max"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "High-end with Pro features",
                            ImagePath = "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2025/09/iPhone-17-Pro2.jpg",
                            Price = 1299f,
                            Quantity = 60,
                            Title = "iPhone 17 Pro"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Standard flagship",
                            ImagePath = "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2025/09/iPhone-17.jpg",
                            Price = 999f,
                            Quantity = 70,
                            Title = "iPhone 17"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Description = "New ultra-thin iPhone Air design",
                            ImagePath = "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2025/09/iPhone-Air.jpg",
                            Price = 1099f,
                            Quantity = 55,
                            Title = "iPhone Air"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Description = "Mid-range Apple, compact size",
                            ImagePath = "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2025/02/Apple-iPhone-16e.jpg",
                            Price = 799f,
                            Quantity = 80,
                            Title = "iPhone 16e"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            Description = "Previous generation Pro",
                            ImagePath = "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2024/09/iphone-16-pro-2.jpg",
                            Price = 1199f,
                            Quantity = 40,
                            Title = "iPhone 16 Pro"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Description = "Previous generation standard",
                            ImagePath = "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2024/09/iPhone-16-1.jpg",
                            Price = 899f,
                            Quantity = 65,
                            Title = "iPhone 16"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            Description = "Samsung top-flagship 2025",
                            ImagePath = "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2025/01/Samsung-Galaxy-S25-Ultra-5G.jpg",
                            Price = 1399f,
                            Quantity = 30,
                            Title = "Samsung Galaxy S25 Ultra"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2,
                            Description = "S25 plus model",
                            ImagePath = "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2025/01/Samsung-Galaxy-S25-Plus-5G.jpg",
                            Price = 1199f,
                            Quantity = 45,
                            Title = "Samsung Galaxy S25+"
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2,
                            Description = "Base S25 model",
                            ImagePath = "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2025/01/Samsung-Galaxy-S23-5G.jpg",
                            Price = 999f,
                            Quantity = 60,
                            Title = "Samsung Galaxy S25"
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 2,
                            Description = "Foldable premium",
                            ImagePath = "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2025/07/Samsung-Galaxy-Z-Fold7-3.jpg",
                            Price = 1899f,
                            Quantity = 20,
                            Title = "Samsung Galaxy Z Fold 7"
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 2,
                            Description = "Foldable (flip style)",
                            ImagePath = "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2024/07/samsung-galaxy-z-fold6.jpg",
                            Price = 1299f,
                            Quantity = 25,
                            Title = "Samsung Galaxy Z Flip 6"
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 2,
                            Description = "Mid-range A-series",
                            ImagePath = "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2024/03/Samsung-Galaxy-A55-2.jpg",
                            Price = 499f,
                            Quantity = 100,
                            Title = "Samsung Galaxy A55 5G"
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 2,
                            Description = "More affordable mid-range",
                            ImagePath = "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2024/03/Samsung-Galaxy-A35-1.jpg",
                            Price = 399f,
                            Quantity = 120,
                            Title = "Samsung Galaxy A35 5G"
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 3,
                            Description = "Xiaomi top flagship 2025",
                            ImagePath = "https://i02.appmifile.com/492_operatorx_operatorx_opx/02/03/2025/5667c36c15d47b90d0faa7ac23c9f276.png?f=webp",
                            Price = 1299f,
                            Quantity = 35,
                            Title = "Xiaomi 15 Ultra"
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 3,
                            Description = "Standard flagship version",
                            ImagePath = "https://i02.appmifile.com/339_operatorx_operatorx_opx/02/03/2025/73371d9d0ca9843bcab6875541dc2905.png?thumb=1&w=1000&f=webp&q=85",
                            Price = 1099f,
                            Quantity = 50,
                            Title = "Xiaomi 15"
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 3,
                            Description = "Foldable Flip",
                            ImagePath = "https://i02.appmifile.com/562_operatorx_operatorx_opx/26/09/2024/dbd8ab2e47beb33c1e0b9aa96287b35c.png?thumb=1&w=1000&f=webp&q=85",
                            Price = 1399f,
                            Quantity = 20,
                            Title = "Xiaomi Mix Flip"
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 3,
                            Description = "Prior Ultra model, still strong",
                            ImagePath = "https://i02.appmifile.com/91_operatorx_operatorx_opx/24/02/2024/4eafcd40186edde466860564f9ff71e9.png?thumb=1&w=600&f=webp&q=85",
                            Price = 1199f,
                            Quantity = 40,
                            Title = "Xiaomi 14 Ultra"
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 3,
                            Description = "Value / performance-oriented",
                            ImagePath = "https://i02.appmifile.com/602_operatorx_operatorx_opx/27/03/2025/7f55fcb97ad2db5405139b5c6b241d20.png?thumb=1&w=600&f=webp&q=85",
                            Price = 699f,
                            Quantity = 80,
                            Title = "Xiaomi POCO F7 Ultra"
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 3,
                            Description = "High mid-range Redmi",
                            ImagePath = "https://i02.appmifile.com/177_operatorx_operatorx_opx/10/01/2025/9e49d2cf6f1afe7ab8255aef590af500.png?thumb=1&w=1000&f=webp&q=85",
                            Price = 499f,
                            Quantity = 90,
                            Title = "Redmi Note 14 Pro"
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 3,
                            Description = "Flagship just before 15 series",
                            ImagePath = "https://i02.appmifile.com/976_operatorx_operatorx_opx/23/02/2024/c4866f7bdd20c6ed7acf6082417dd340.png?thumb=1&w=600&f=webp&q=85",
                            Price = 999f,
                            Quantity = 45,
                            Title = "Xiaomi 14"
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 4,
                            Description = "Flagship ultra camera set",
                            ImagePath = "https://www.oppo.com/content/dam/oppo/common/mkt/v2-2/find-x8-series-en/find-x8-pro/listpage/432-600-black.png",
                            Price = 1399f,
                            Quantity = 30,
                            Title = "OPPO Find X8 Ultra"
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 4,
                            Description = "Pro performance",
                            ImagePath = "https://www.oppo.com/content/dam/oppo/common/mkt/v2-2/find-x8-series-en/find-x8-pro/listpage/432-600-white.png",
                            Price = 1299f,
                            Quantity = 35,
                            Title = "OPPO Find X8 Pro"
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 4,
                            Description = "More accessible flagship",
                            ImagePath = "https://www.oppo.com/content/dam/oppo/common/mkt/v2-2/find-x8-series-en/find-x8/listpage/436-600-white-v2.png",
                            Price = 1099f,
                            Quantity = 50,
                            Title = "OPPO Find X8"
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 4,
                            Description = "Premium mid-range Reno series",
                            ImagePath = "https://www.oppo.com/content/dam/oppo/common/mkt/v2-2/reno14-series/list-page/reno14-pro/448-600-white.png",
                            Price = 899f,
                            Quantity = 60,
                            Title = "OPPO Reno 14 Pro 5G"
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 4,
                            Description = "Mid-range Reno",
                            ImagePath = "https://www.oppo.com/content/dam/oppo/common/mkt/v2-2/reno14-series/list-page/reno14/448-600-green.png",
                            Price = 699f,
                            Quantity = 80,
                            Title = "OPPO Reno 14 5G"
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 4,
                            Description = "Foldable premium",
                            ImagePath = "https://www.oppo.com/content/dam/oppo/common/mkt/v2-2/oppo-find-n5-en/listpage/427-600-white.png",
                            Price = 1499f,
                            Quantity = 15,
                            Title = "OPPO Find N5"
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 4,
                            Description = "Value mid-high",
                            ImagePath = "https://www.oppo.com/content/dam/oppo/common/mkt/v2-2/reno13-series/list-page/reno13-pro-5g/purple.png",
                            Price = 799f,
                            Quantity = 90,
                            Title = "OPPO Reno 13 Pro 5G"
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 5,
                            Description = "Honor flagship, Snapdragon 8 Elite",
                            ImagePath = "https://www.honor.com/content/dam/honor/common/product-list/product-series/honor-magic7/honor-magic7-id-white-back.png",
                            Price = 1199f,
                            Quantity = 30,
                            Title = "Honor Magic 7 Pro"
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 5,
                            Description = "Foldable from Honor",
                            ImagePath = "https://www.honor.com/content/dam/honor/common/product-list/product-series/honor-magic-v5/honor-magic-v5-id-gold.png",
                            Price = 1599f,
                            Quantity = 20,
                            Title = "Honor Magic V5"
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 5,
                            Description = "Mid-range strong offering",
                            ImagePath = "https://www.honor.com/content/dam/honor/common/product-list/product-series/honor-400-pro/honor-400-pro-id-gary-back.png",
                            Price = 599f,
                            Quantity = 60,
                            Title = "Honor 400 Pro"
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 5,
                            Description = "Earlier flagship",
                            ImagePath = "https://www.honor.com/content/dam/honor/common/product-list/product-series/honor-magic6-pro/honor-magic6-pro-id-green-back.png",
                            Price = 1099f,
                            Quantity = 25,
                            Title = "Honor Magic 6 Pro"
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryId = 5,
                            Description = "Upper mid-range",
                            ImagePath = "https://www.honor.com/content/dam/honor/common/product-list/product-series/honor-x9c-smart/honor-x9c-smart-cyan-back.png",
                            Price = 499f,
                            Quantity = 80,
                            Title = "Honor X9c 5G"
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryId = 5,
                            Description = "Gaming style mid-range",
                            ImagePath = "https://www.honor.com/content/dam/honor/common/product-list/product-series/honor-90-lite/honor-90-lite-lake-back.png",
                            Price = 699f,
                            Quantity = 40,
                            Title = "Honor 90 GT"
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryId = 5,
                            Description = "Value / budget-mid",
                            ImagePath = "https://www.honor.com/content/dam/honor/common/product-list/product-series/honor-magic7/honor-magic7-id-black-front.png",
                            Price = 499f,
                            Quantity = 90,
                            Title = "Honor Magic 7 Lite"
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "john.smith@example.com",
                            FirstName = "John",
                            LastName = "Smith",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "emily.johnson@example.com",
                            FirstName = "Emily",
                            LastName = "Johnson",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "michael.brown@example.com",
                            FirstName = "Michael",
                            LastName = "Brown",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "sarah.williams@example.com",
                            FirstName = "Sarah",
                            LastName = "Williams",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "david.jones@example.com",
                            FirstName = "David",
                            LastName = "Jones",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "olivia.miller@example.com",
                            FirstName = "Olivia",
                            LastName = "Miller",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "daniel.davis@example.com",
                            FirstName = "Daniel",
                            LastName = "Davis",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 8,
                            Email = "sophia.garcia@example.com",
                            FirstName = "Sophia",
                            LastName = "Garcia",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 9,
                            Email = "james.martinez@example.com",
                            FirstName = "James",
                            LastName = "Martinez",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 10,
                            Email = "isabella.hernandez@example.com",
                            FirstName = "Isabella",
                            LastName = "Hernandez",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 11,
                            Email = "william.lopez@example.com",
                            FirstName = "William",
                            LastName = "Lopez",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 12,
                            Email = "mia.gonzalez@example.com",
                            FirstName = "Mia",
                            LastName = "Gonzalez",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 13,
                            Email = "benjamin.wilson@example.com",
                            FirstName = "Benjamin",
                            LastName = "Wilson",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 14,
                            Email = "charlotte.anderson@example.com",
                            FirstName = "Charlotte",
                            LastName = "Anderson",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 15,
                            Email = "ethan.thomas@example.com",
                            FirstName = "Ethan",
                            LastName = "Thomas",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 16,
                            Email = "amelia.taylor@example.com",
                            FirstName = "Amelia",
                            LastName = "Taylor",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 17,
                            Email = "alexander.moore@example.com",
                            FirstName = "Alexander",
                            LastName = "Moore",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 18,
                            Email = "harper.jackson@example.com",
                            FirstName = "Harper",
                            LastName = "Jackson",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 19,
                            Email = "henry.martin@example.com",
                            FirstName = "Henry",
                            LastName = "Martin",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 20,
                            Email = "evelyn.lee@example.com",
                            FirstName = "Evelyn",
                            LastName = "Lee",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 21,
                            Email = "matthew.perez@example.com",
                            FirstName = "Matthew",
                            LastName = "Perez",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 22,
                            Email = "ella.thompson@example.com",
                            FirstName = "Ella",
                            LastName = "Thompson",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 23,
                            Email = "samuel.white@example.com",
                            FirstName = "Samuel",
                            LastName = "White",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 24,
                            Email = "abigail.harris@example.com",
                            FirstName = "Abigail",
                            LastName = "Harris",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 25,
                            Email = "joseph.sanchez@example.com",
                            FirstName = "Joseph",
                            LastName = "Sanchez",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 26,
                            Email = "scarlett.clark@example.com",
                            FirstName = "Scarlett",
                            LastName = "Clark",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 27,
                            Email = "christopher.ramirez@example.com",
                            FirstName = "Christopher",
                            LastName = "Ramirez",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 28,
                            Email = "grace.lewis@example.com",
                            FirstName = "Grace",
                            LastName = "Lewis",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 29,
                            Email = "andrew.robinson@example.com",
                            FirstName = "Andrew",
                            LastName = "Robinson",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 30,
                            Email = "chloe.walker@example.com",
                            FirstName = "Chloe",
                            LastName = "Walker",
                            Password = "Pass@123"
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.Product", b =>
                {
                    b.HasOne("OnlineStore.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineStore.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
